# The title of your site (will be shown in the browser tab)
title: Programming Paradigms and Languages

# The name of your site (will be shown in the header)
name: Paradigms-Py

# A short description of your site for SEO
description: A university course on programming paradigms using Python.

# The markdown processor
markdown: GFM

# ----------------- THEME CONFIGURATION ----------------- #
# Set the theme
plugins:
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs

# (Optional) Set a default color scheme. 
# 'light', 'dark', or omit to respect user's browser/OS setting.
# color_scheme: light

# (Optional but Recommended) Add a link to the GitHub repo in the header
aux_links:
  "View on GitHub":
    - "https://github.com/karlo-babic/paradigms-py"